// Supabase Configuration
// Thay thế với thông tin project của bạn

const SUPABASE_CONFIG = {
    // URL của Supabase project
    url: 'YOUR_SUPABASE_URL',
    
    // Public key (anon key) - an toàn để dùng ở frontend
    anonKey: 'YOUR_SUPABASE_ANON_KEY',
    
    // Tên bảng dữ liệu
    tableName: 'survey_responses'
};

// SQL để tạo table trong Supabase SQL Editor
const CREATE_TABLE_SQL = `
-- Tạo bảng survey_responses
CREATE TABLE IF NOT EXISTS survey_responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    name TEXT NOT NULL,
    memory TEXT,
    topic TEXT,
    goal TEXT,
    style TEXT,
    struggle TEXT,
    timestamp TEXT
);

-- Thêm RLS (Row Level Security) policy
ALTER TABLE survey_responses ENABLE ROW LEVEL SECURITY;

-- Cho phép anyone insert dữ liệu vào bảng
CREATE POLICY "Anyone can insert survey responses" ON survey_responses
    FOR INSERT WITH CHECK (true);

-- Cho phép anyone xem dữ liệu (có thể thay đổi thành chỉ admin)
CREATE POLICY "Anyone can view survey responses" ON survey_responses
    FOR SELECT USING (true);

-- Tạo index để tối ưu performance
CREATE INDEX IF NOT EXISTS idx_survey_responses_created_at ON survey_responses(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_survey_responses_topic ON survey_responses(topic);
`;

// Export để sử dụng
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { SUPABASE_CONFIG, CREATE_TABLE_SQL };
}
